package com.whatsgb.gbwhatsappgbapp.gbwhatsversionnew;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.widget.LinearLayout;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.google.android.material.appbar.MaterialToolbar;
import com.whatsgb.gbwhatsappgbapp.gbwhatsversionnew.adapter.EmoticonsAdaptersdfs;
import com.whatsgb.gbwhatsappgbapp.gbwhatsversionnew.model.EmotiModeldsfdsf;

import java.util.ArrayList;
import java.util.List;

public class WhatsEmoticonsActivityas extends AppCompatActivity {

    //new
    public static Context context;

    //Preference
    private static PrefManagersd prf;

    List<EmotiModeldsfdsf> emotiModeldsfdsfs = new ArrayList<>();
    RecyclerView recyclerView;
    String name;
    int position;
    MaterialToolbar materialToolbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.whatsactivity_emoticons);
        materialToolbar = findViewById(R.id.toolbar);
        materialToolbar.setVisibility(View.VISIBLE);
        setSupportActionBar(materialToolbar);
        if (getSupportActionBar() != null){
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        }

        materialToolbar.setNavigationOnClickListener(view -> {
            finishAfterTransition();
        });

        context = getApplicationContext();

        prf = new PrefManagersd(context);


        this.name = getIntent().getStringExtra("image");
        this.position = getIntent().getIntExtra("P", 0);
        int i = this.position;
        if (i == 0) {
            getSupportActionBar().setTitle("Love");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(1  , "♥‿♥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(2  , "★~(◡‿◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(3  , "(ノ・ω・)ノ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(4  , "★~(◡︿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(5  , "♥╣[-_-]╠♥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(6  , "（⌒_⌒）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(7  , ">‿‿◕"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(8  , "★~(◡△◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(9  , "⎝ᄽ⏝⏠⎠"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(10 , "(~￣▽￣)~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(11 , "★~(◡﹏⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(12 , "★~(◠﹏◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(13 , "(◕‿-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(14 , "★~(◡﹏◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(15 , "★~(◠﹏⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(16 , "★~(◠ω◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(17 , "♥╭╮♥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(18 , "★~(◡‿⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(19 , "(｡♥‿♥｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(20 , "★~(◡△⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(21 , "★~(◠‿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(22 , "v(=∩_∩=)ﾌ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(23 , "♥╭╮♥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(24 , "(ΘεΘ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(25 , "★~(◡‿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(26 , "★~(◡ω◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(27 , "( ^▽^)σ)~O~)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(28 , "★~(◠△◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(29 , "(✿ ♥‿♥)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(30 , "★~(◠△⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(31 , "(╯3╰)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(32 , "★~(◠ω⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(33 , "★~(◡△◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(34 , "★~(◡﹏◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(35 , "(●´ω｀●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(36 , "★~(◡︿⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(37 , "☼.☼"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(38 , "★~(◠︿⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(39 , "★~(◡ω◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(40 , "ヘ(^_^ヘ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(41 , "(n˘v˘•)¬"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(42 , "( ･_･)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(43 , "★~(◡ω⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(44 , "(●♡∀♡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(45 , "(｡♥‿♥｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(46 , "(♥ω♥ ) ~♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(47 , "(♥ω♥*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(48 , "(✿ ♥‿♥)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(49 , "✿♥‿♥✿"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(50 , "乂❤‿❤乂"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(51 , "٩(♡ε♡ )۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(52 , "ლζ*♡ε♡*ζლ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(53 , "⊂（♡⌂♡）⊃"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(54 , "(๑♡3♡๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(55 , "(๑♡⌓♡๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(56 , "♱♡‿♡♰"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(57 , "⊆♥_㇁♥⊇"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(58 , "(●♡∀♡))ヾ☆*。"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(59 , "໒( ♥ ◡ ♥ )७"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(60 , "༼♥ل͜♥༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(61 , "(灬♥ω♥灬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(62 , "(‘∀’●)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(63 , "(´∀｀)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(64 , "（*´▽｀*）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(65 , "（´・｀ ）♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(66 , "（´ω｀♡%）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(67 , "♥(ˆ⌣ˆԅ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(68 , "꒰˘̩̩̩⌣˘̩̩̩๑꒱♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(69 , "ლ(́◉◞౪◟◉‵ლ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(70 , "⸌̷̻( ᷇ॢ〰ॢ ᷆◍)⸌̷̻♡⃛"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(71 , "₍՞◌′ᵕ‵ू◌₎♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(72 , "♡ฅ(ᐤˊ꒳ฅˋᐤ♪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(73 , "ʚ♡⃛ɞ(ू•ᴗ•ू❁)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(74 , "❣⃛(❛ั◡˜๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(75 , "( ˭̵̵̵̵͈́◡ु͂˭̵̵̵͈̀ )ˉ̞̭♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(76 , "♡(ŐωŐ人)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(77 , "❤⃛ヾ(๑❛ ▿ ◠๑ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(78 , "（*’∀’人）♥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(79 , "(°◡°♡).:｡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(80 , "ʸ(➜◡ु⚈᷉)♡⃛"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(81 , "ˉ̞̭(′͈∨‵͈♡)˄̻ ̊"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(82 , "◟(◔ั₀◔ั )◞ ༘♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(83 , "φ(ﾟ ωﾟ//）♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(84 , "ʸ(ᴖ́◡ु⚈᷉)♡⃛"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(85 , "ꉂ (′̤ॢ∀ ू‵̤๑))ˉ̞̭♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(86 , "♡♡+.ﾟ(￫ε￩*)ﾟ+.ﾟ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(87 , "꒰✪ૢꇵ✪ૢ꒱ෆ⃛"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(88 , "(●´□`)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(89 , "(｡･ω･｡)ﾉ♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(90 , "(｡’▽’｡)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(91 , "（●´∀｀）ノ♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(92 , "₍₍ ( ๑॔˃̶◡ ˂̶๑॓)◞♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(93 , "(๑・ω-)～♥”"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(94 , "(๑°꒵°๑)･*♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(95 , "～(^з^)-♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(96 , "(๑ˊ͈ ॢꇴ ˋ͈)〜♡॰ॱ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(97, "(ෆ ͒•∘̬• ͒)◞"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(98, "♡(㋭ ਊ ㋲)♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(99, "( •ॢ◡-ॢ)-♡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(100, "(●’ᴗ’σ)σணღ*")); }
        else if (i == 1) {
            getSupportActionBar().setTitle("Happy");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(101, "(◕‿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(102, "(◠‿◠✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(103, "(◠﹏◠✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(104, "（＊＾Ｕ＾）人（≧Ｖ≦＊）/"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(105, "ôヮô"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(106, "∧( ‘Θ’ )∧"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(107, "(¤﹏¤)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(108, "●‿●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(109, "ʕ·ᴥ·ʔ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(110, "＼（＾○＾）人（＾○＾）／"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(111, "ヾ(＠⌒▽⌒＠)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(112, "(°∀°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(113, "ヾ｜￣ー￣｜ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(114, "(☉‿☉✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(115, "┏(＾0＾)┛┗(＾0＾) ┓"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(116, "(◡‿◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(117, "✿◕ ‿ ◕✿"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(118, "ヽ(‘ ∇‘ )ノ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(119, "☆(❁‿❁)☆"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(120, "❀◕ ‿ ◕❀"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(121, "ヽ(^◇^*)/"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(122, "(•⊙ω⊙•)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(123, "!⑈ˆ~ˆ!⑈"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(124, "(*^ -^*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(125, "(⊙‿⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(126, "◕3◕"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(127, "(ﾟヮﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(128, "¢‿¢"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(129, "ヅ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(130, "●ᴥ●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(131, "(∪ ◡ ∪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(132, "≖‿≖"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(133, "≧◡≦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(134, "٩◔‿◔۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(135, "｡◕ ‿ ◕｡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(136, "ヾ(＠＾▽＾＠)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(137, "◃┆◉◡◉┆▷"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(138, "(✿◠‿◠)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(139, "(￣ｰ￣)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(140, "╰(◡‿◡✿╰)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(141, "~,~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(142, "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(143, "(*~▽~)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(144, "❀‿❀"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(145, "◕‿◕"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(146, "(^L^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(147, "(^▽^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(148, "◕ ◡ ◕"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(149, "(◕‿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(150, "（ ；´Д｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(151, "⊙﹏⊙"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(152, "✿｡✿"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(153, "ヽ(゜∇゜)ノ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(154, "｡(✿‿✿)｡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(155, "(´ー｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(156, "ツ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(157, "q(❂‿❂)p"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(158, "( ́ ◕◞ε◟◕`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(159, "☆(◒‿◒)☆"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(160, "(∩▂∩)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(161, "(¬‿¬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(162, "(^Ｏ^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(163, "ʘ‿ʘ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(164, "（’◎’）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(165, "(◜௰◝)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(166, "(^ｰ^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(167, "(o´ω｀o)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(168, "(^з^)-☆"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(169, "(◕ω◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(170, "(づ｡◕‿‿◕｡)づ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(171, "(ﾟ▽^*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(172, "(⌒o⌒)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(173, "(｡◕‿◕｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(174, "ت"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(175, "(. ﾟーﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(176, "१✌˚◡˚✌५"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(177, "＼(●~▽~●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(178, "(*˘︶˘*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(179, "(✪㉨✪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(180, "(ᅌᴗᅌ* )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(181, "^L^"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(182, "(･ｪ-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(183, "＼(*^▽^*)/"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(184, "(◠△◠✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(185, "( ಠ◡ಠ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(186, "(〃^∇^)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(187, "^^"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(188, "|◔◡◉|"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(189, "(●⌒∇⌒●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(190, "⊂◉‿◉つ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(191, ".ʕʘ‿ʘʔ."));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(192, "(*・∀・*)人(*・∀・*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(193, "＼(^-^)／"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(194, "∩(︶▽︶)∩"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(195, "（☉∀☉）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(196, "(´ω｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(197, "●﹏●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(198, "（ ´∀｀）☆"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(199, "•ᴥ•"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(200, "✿◕ ‿ ◕✿")); }
        else if (i == 2) {
            getSupportActionBar().setTitle("Music");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(201, "ヾ(´〇`)ﾉ♪♪♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(202, "ヘ(￣ω￣ヘ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(203, "(〜￣▽￣)〜"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(204, "〜(￣▽￣〜)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(205, "ヽ(o´∀`)ﾉ♪♬"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(206, "(ﾉ≧∀≦)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(207, "♪ヽ(^^ヽ)♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(208, "♪(/_ _ )/♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(209, "♪♬((d⌒ω⌒b))♬♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(210, "└(￣-￣└))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(211, "((┘￣ω￣)┘"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(212, "√(￣‥￣√)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(213, "└(＾＾)┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(214, "┌(＾＾)┘"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(215, "＼(￣▽￣)＼"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(216, "／(￣▽￣)／"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(217, "(￣▽￣)/♫•*¨*•.¸¸♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(218, "(^_^♪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(219, "(~˘▽˘)~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(220, "~(˘▽˘~)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(221, "ヾ(⌐■_■)ノ♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(222, "(〜￣△￣)〜"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(223, "(~‾▽‾)~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(224, "~(˘▽˘)~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(225, "乁( • ω •乁)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(226, "(｢• ω •)｢"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(227, "⁽⁽◝( • ω • )◜⁾⁾"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(228, "✺◟( • ω • )◞✺"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(229, "♬♫♪◖(● o ●)◗♪♫♬"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(230, "( ˘ ɜ˘) ♬♪♫"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(231, "♪♪♪ ヽ(ˇ∀ˇ )ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(232, "(o・★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(233, "(☆￢o)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(234, "(^_^♪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(235, "(´△｀)♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(236, "ρ(o＜★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(237, "ρ(o＾★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(238, "(☆￣o)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(239, "(☆∩o)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(240, "(☆≧o)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(241, "(☆Θo)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(242, "(´0｀)q"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(243, "ρ(oμ★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(244, "（＾Ｏ＾☆♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(245, "（＾3＾）~♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(246, "（*´▽｀*）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(247, "ρ（ーoー)♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(248, "（^Ｏ^）～♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(249, "ρ(o δ★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(250, "ρ(＾o^)♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(251, "ρ（^o^）♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(252, "ρ（＾o＾）♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(253, "♫꒰･◡･๑꒱"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(254, "(o^^o)♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(255, "♫♪˙‿˙♫♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(256, "♪(ﾉε｀●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(257, "ρ(^^ )♭"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(258, "♪～(￣ε￣)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(259, "♪(´ε｀ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(260, "（＊＾ω＾）♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(261, "≧(´▽｀)≦"));        }
        else if (i == 3) {
            getSupportActionBar().setTitle("Animals");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(262, "(^^ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(263, "(〃▽〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(264, "(ノ▽〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(265, "（/｡＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(266, "(/ω＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(267, "(Ŏ艸Ŏ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(268, "(^^;)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(269, "(〃ー〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(270, "(〃ω〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(271, "(〃艸〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(272, "(´つヮ⊂)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(273, "(♡´艸`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(274, "(／≧ω＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(275, "ʕ*ﾉᴥﾉʔ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(276, "(/へ＼*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(277, "(*ﾉ▽ﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(278, "(*ﾉωﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(279, "(*ﾉдﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(280, "(´～｀ヾ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(281, "(ﾉ∇≦*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(282, "(‘-’*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(283, "(^◇^；)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(284, "|▽//)ゝ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(285, "(〃´∀｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(286, "ꈍ .̮ ꈍ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(287, "(〃∀〃)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(288, "( 〃．．)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(289, "(｡･･｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(290, "|´∀｀●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(291, "((-ω-｡)(｡-ω-))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(292, "ＯＴＬ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(293, "ｏｒｚ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(294, "＿ﾉフ○"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(295, "(￣Д￣"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(296, "(´Д⊂"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(297, "（－－；"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(298, "（´。｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(299, "（￣Ω￣）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(300, "(A´Å｀"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(301, "A^-^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(302, "(∋д∈)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(303, "(・。-;"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(304, "（´・｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(305, "(*Q*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(306, "(／０￣)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(307, "＿|￣|○"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(308, "(-。-;"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(309, "(´Д｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(310, "(;´Д｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(311, "（＾。＾；）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(312, "(≧∀≦ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(313, "(-ω-ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(314, "(≧ω≦)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(315, "(｀-´)>"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(316, "∠(｀∪´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(317, "|`Д´)＞"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(318, "(≧∇≦)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(319, "(・∀-d)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(320, "(`Д´)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(321, "|▼皿▼)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(322, "(・∧‐)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(323, "(●・ω・)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(324, "ｄ(´▽｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(325, "(*゜－＾)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(326, "(°∀°)ゝ”"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(327, "(*｀Ω´)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(328, "(＞Д＜)ゝ”"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(329, "(=ﾟ▽ﾟ)/"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(330, "('∀`)ゝ”"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(331, "( ｀д´)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(332, "d(￣▽￣o)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(333, "(*>ω<)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(334, "(｀∀´)ゝ”"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(335, "d(´･ω･`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(336, "(*´ω｀*)ノ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(337, "(★´ω｀★)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(338, "(●´･∀･)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(339, "d(*ﾟーﾟ*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(340, "☆(･ω･*)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(341, "(●⌒∇⌒●)b"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(342, "((´д｀))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(343, "((；ﾟДﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(344, "((;ﾟДﾟ))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(345, "(llФｗФ｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(346, "((ﾟДﾟ；))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(347, "((；ﾟェﾟ；))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(348, ":(´◦ω◦｀):"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(349, "(((＾ω＾)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(350, "（（（゜Д゜；）））"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(351, "（（（・×・；）））"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(352, "(((･Α･川)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(353, "((( ；ﾟДﾟ)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(354, "((,,´Θ`,,))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(355, "((o(´∀｀)o))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(356, "《《(ﾟc_ﾟ；)》》"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(357, ":;(∩´﹏`∩);:"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(358, "((((；ﾟДﾟ)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(359, "||lll´Д｀)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(360, "((((；ﾟДﾟ))))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(361, "((ﾟﾟ((Д))ﾟﾟ))"));        }
        else if (i == 4) {
            getSupportActionBar().setTitle("Angry");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(362, "凸(｀0´)凸"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(363, "凸ಠ益ಠ)凸"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(364, "凸(⊙▂⊙✖ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(365, "┌П┐(►˛◄’!)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(366, "凸(-0-メ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(367, "凸(｀⌒´メ)凸"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(368, "凸(｀△´＋）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(369, "( ︶︿︶)_╭∩╮"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(370, "凸(｀ι _´メ）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(371, "凸(>皿<)凸"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(372, "凸(^▼ｪ▼ﾒ^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(373, "t(=n=)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(374, "t(- n -)t"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(375, "凸(¬‿¬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(376, "┌∩┐(◣_◢)┌∩┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(377, "┌∩┐(ಠ_ಠ)┌∩┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(378, "╭∩╮(︶︿︶)╭∩╮"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(379, "╭∩╮(-_-)╭∩╮"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(380, "( ≧Д≦)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(381, "(；￣Д￣）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(382, "(;¬_¬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(383, "（；¬＿¬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(384, "(｡+･`ω･´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(385, "｡゜(｀Д´)゜｡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(386, "(　ﾟДﾟ)＜!!"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(387, "(‡▼益▼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(388, "(,,#ﾟДﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(389, "(҂⌣̀_⌣́)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(390, "(；¬д¬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(391, "（;≧皿≦）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(392, "(╬ﾟ◥益◤ﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(393, "(╬⓪益⓪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(394, "[○･｀Д´･○]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(395, "૮( ᵒ̌▱๋ᵒ̌ )ა"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(396, "(⁎˃ᆺ˂)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(397, "(ꐦ°᷄д°᷅)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(398, "((╬●∀●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(399, "(╬ Ò ‸ Ó)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(400, "( >д<)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(401, "(*｀益´*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(402, "(☞◣д◢)☞"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(403, "<(｀^´)>"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(404, "(;｀O´)o"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(405, "(ꐦ ಠ皿ಠ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(406, "（｀Δ´）！"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(407, "(*｀Ω´*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(408, "(╬ಠ益ಠ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(409, "(╬ﾟ◥益◤ﾟ) ╬ﾟ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(410, "(ு⁎ு)྆྆"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(411, "(╬⓪益⓪)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(412, "（╬ಠ益ಠ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(413, "(●o≧д≦)o"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(414, "=͟͟͞͞( •̀д•́)))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(415, "(๑･`▱´･๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(416, "༼ つ ͠° ͟ ͟ʖ ͡° ༽つ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(417, "(☄ฺ◣д◢)☄ฺ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(418, "ꀯ(‴ꑒ᷅⺫ꑒ᷄)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(419, "(#｀皿´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(420, "(｀Д´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(421, "(ﾒﾟ皿ﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(422, "(o｀ﾟ皿ﾟ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(423, "( ╬◣ 益◢)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(424, "（╬ಠ益ಠ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(425, "（♯▼皿▼）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(426, "( ╬◣ 益◢）y━･~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(427, "（○｀Ｏ´○）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(428, "(; ･`д･´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(429, "｜。｀＞Д＜｜"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(430, "(; ･`д･´)​"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(431, "( •̀ω•́ )σ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(432, "o(-`д´- ｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(433, "(´･益･｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(434, "(´Д｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(435, "(¬д¬。)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(436, "（≧▼≦；)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(437, "(ᇂ∀ᇂ╬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(438, "(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(439, "(ू˃̣̣̣̣̣̣o˂̣̣̣̣̣̣ ू)⁼³₌₃"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(440, "（▼へ▼メ）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(441, "｢(#Φ益 Φo)∩"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(442, "s(・｀ヘ´・；)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(443, "s(・｀ヘ´・;)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(444, "Σ(-`Д´-ﾉ；)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(445, "Σ(▼□▼メ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(446, "๛∙᷅῞ॄ∙᷄"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(447, "(°ㅂ° ╬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(448, "( ｰ̀εｰ́ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(449, "(눈_눈)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(450, "(´◣д◢`+)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(451, "(ʘ言ʘ╬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(452, "(Ò 皿 Ó ╬)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(453, "(-̀◞८̯◟-́)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(454, "( ͒˃⌂˂ ͒)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(455, "┌(▀Ĺ̯ ▀-͠ )┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(456, "[⑇⨀ེ⌓⨀ེ•⑇]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(457, "Σ(ﾟд´;ﾉ)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(458, "(-̀◞▥◟-́)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(459, "☜(`o´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(460, "(◎益◎;)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(461, "(@益@ .:;)"));        }
        else if (i == 5) {
            getSupportActionBar().setTitle("Sad");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(462, "ಥ_ಥ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(463, "(-’๏_๏’-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(464, "˚⌇˚"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(465, "o(╥﹏╥)o"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(466, "(⊙﹏⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(467, "●︿●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(468, "(一。一;;）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(469, "(╯︵╰,)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(470, "(︶︹︺)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(471, "(◡﹏◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(472, "(✖﹏✖)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(473, "‘︿’"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(474, "v( ‘.’ )v"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(475, "◄.►"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(476, "(ㄒoㄒ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(477, "⊙︿⊙"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(478, "(◕︿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(479, "ਉ_ਉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(480, "┐(‘～`；)┌"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(481, "(︶︹︺)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(482, "흫_흫"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(483, "ب_ب"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(484, "╮(─▽─)╭"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(485, "ಥ‿ಥ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(486, "(-’_’-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(487, "(╥╥)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(488, "(•̪●)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(489, "(∩︵∩)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(490, "(o_-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(491, "(｡-_-｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(492, "(╯_╰)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(493, "(╥_╥)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(494, "v(ಥ ̯ ಥ)v"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(495, "<('.'<)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(496, "ಠ,ಥ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(497, "(◕︵◕)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(498, "(´ヘ｀()"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(499, "(✖╭╮✖)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(500, "(◕﹏◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(501, "(+_+)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(502, "★~(◠︿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(503, "(*´д｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(504, "(◡△◡✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(505, "٩(×̯×)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(506, "(ノ_・。)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(507, "┐(‘～`；)┌"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(508, "(つд｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(509, "(✖╭╮✖)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(510, "ಥ⌣ಥ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(511, "இ_இ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(512, "✖‿✖"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(513, "( ≧Д≦)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(514, "((´д｀))"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(515, "(∩︵∩)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(516, "(▰˘︹˘▰)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(517, "(✖╭╮✖)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(518, "(‘A`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(519, "(︶︹︺)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(520, "(＠´＿｀＠)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(521, "（´＿｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(522, "(⊙︿⊙✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(523, "(⌣_⌣”)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(524, "(▰︶︹︺▰)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(525, "~(｡☉︵ ಠ@)>"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(526, "⊙︿⊙"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(527, "ヽ(●ﾟ´Д｀ﾟ●)ﾉﾟ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(528, "(.﹒︣︿﹒︣.)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(529, "(Θ︹Θ)ს"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(530, "٩꒰´·⌢•｀꒱۶⁼³₌₃"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(531, ":: ˓(ᑊᘩᑊ⁎) ::"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(532, "˓˓(ᑊᘩᑊ⁎)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(533, "(๑◕︵◕๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(534, "( .. )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(535, "(｡•́︿•̀｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(536, "(´°ω°`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(537, "੨( ･᷄ ︵･᷅ )ｼ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(538, "꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(539, "(⌯˃̶᷄ ﹏ ˂̶᷄⌯)ﾟ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(540, "(っ- ‸ – ς)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(541, "(๑′°︿°๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(542, "⊛ठ̯⊛"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(543, "ಠ╭╮ಠ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(544, "( ◞᷄દ◟᷅ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(545, "(oꆤ︵ꆤo)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(546, "ಗಾ ﹏ ಗಾ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(547, "ᵟຶᴖ ᵟຶ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(548, "(⋅⃘˕̭⋅⃘)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(549, "ōۃō"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(550, "( ⁍᷄⌢̻⁍᷅ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(551, "(.﹒︠₋﹒︡.)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(552, "(˵¯͒⌢͗¯͒˵)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(553, "☹ै"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(554, "(　´_ﾉ` )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(555, "ʕ ಡ ﹏ ಡ ʔ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(556, "●︿●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(557, "(◕︿◕✿)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(558, "ਉ_ਉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(559, "༶ඬ༝ඬ༶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(560, "(;-_-)/"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(561, "(oT-T)尸"));        }
        else if (i == 6) {
            getSupportActionBar().setTitle("Sleeping");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(562, "[(－－)]..zzZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(563, "(－_－) zzZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(564, "(∪｡∪)｡｡｡zzZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(565, "(－ω－) zzZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(566, "(￣o￣) zzZZzzZZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(567, "(( _ _ ))..zzzZZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(568, "(￣ρ￣)..zzZZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(569, "(－.－)...zzz"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(570, "(＿ ＿*) Z z z"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(571, "(x . x) ~~zzZ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(572, "【:εω"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(573, "(冫༵、)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(574, "(ᴗ˳ᴗ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(575, "(´～`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(576, "( ⓥωⓥ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(577, "(:˒[￣]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(578, "(*-ω-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(579, "(︶｡︶✽)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(580, "(:3ぅ　)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(581, "(¦ꒉ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(582, "(¦ꀦ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(583, "⌈▓͟⌉ꆟ)ꍞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(584, "（;´_ヘ;）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(585, "（´○｀）～ゝ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(586, "(¦ꃎ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(587, "(¦ꎌ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(588, "(¦ꃆ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(589, "(¦ꄰ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(590, "⌈▒͟⌉ꅼ)ꍞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(591, "＼（´Ｏ｀）／"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(592, "（◎´〇｀◎）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(593, "(´-εヾ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(594, "(｡し_し｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(595, "(｡´-д-)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(596, "(*´ο`*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(597, "川｡μ_μ)σ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(598, "(｡v_v｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(599, "(๑ᵕ⌓ᵕ̤)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(600, "(¦ꃩ[▓▓]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(601, "꒰◍ᐡᐤᐡ◍꒱"));        }
        else if (i == 7) {
            getSupportActionBar().setTitle("Excited");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(602, "≧ω≦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(603, "୧⍢⃝୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(604, "(⊙ᗜ⊙)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(605, "โ๏∀๏ใ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(606, "(≧∀≦)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(607, "۹⌤_⌤۹"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(608, "୧☉□☉୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(609, "(⊙ꇴ⊙)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(610, "(´∀`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(611, "（・ｗ・）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(612, "(ᗒᗨᗕ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(613, "ʘ ͜ʖ ʘ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(614, "(≧∇≦*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(615, "(*≧▽≦)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(616, "۹(ÒہÓ)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(617, "(ﾉ･ｪ･)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(618, "٩(^ᴗ^)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(619, "б（＞ε＜）∂"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(620, "(⌬̀⌄⌬́)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(621, "٩(θ‿θ)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(622, "ヽ(＾Д＾)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(623, "(★^O^★)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(624, "（๑✧∀✧๑）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(625, "(*≧∀≦*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(626, "٩(●ᴗ●)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(627, "⸍⚙̥ꇴ⚙̥⸌"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(628, "(๑>ᴗ<๑)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(629, "۹(˒௰˓)۶"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(630, "(* >ω<)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(631, "＼（Ｔ∇Ｔ）／"));        }
        else if (i == 8) {
            getSupportActionBar().setTitle("Hungry");
            emotiModeldsfdsfs = new ArrayList<>();
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(632, "―●○◎-"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(633, "―⊂ZZZ⊃"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(634, "（￣ｗ￣）Ψ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(635, "◥█̆̈◤࿉∥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(636, "(＾-＾)＿日"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(637, "(。・・)_且"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(638, "(＃´ー´)旦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(639, "且_(・_・ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(640, "(　ﾟДﾟ)⊃旦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(641, "( -_-)旦~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(642, "(*^◇^)_旦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(643, "(*･∀･)_Ω~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(644, "~旦_(^O^ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(645, "(　 ゜Д゜)⊃旦"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(646, "~~旦⊂(･∀･ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(647, "ｰ( ￣▽)_皿~~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(648, "(*｀▽´)_旦~~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(649, "~~旦_(･o･;)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(650, "~(=^‥^)_旦~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(651, "且_(ﾟ◇ﾟ；)ノﾞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(652, "(*´ｪ｀*)っ旦~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(653, "( ・・)つ-●●●"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(654, "( ^-^)_旦””"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(655, "((((´∀｀)＿旦～"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(656, "( ´･ω･`)_且~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(657, "(*´-ω)o旦~┏┓"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(658, "(*´・ω)o旦~┏┓"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(659, "~~匸Pヽ(･ω･｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(660, "(○^ω^)_旦~~♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(661, "~~旦_(-ω-｀｡)"));        }
        else if (i == 9) {
            getSupportActionBar().setTitle("Shy");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(662, "(^^ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(663, "(〃▽〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(664, "(ノ▽〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(665, "（/｡＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(666, "(/ω＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(667, "(Ŏ艸Ŏ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(668, "(^^;)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(669, "(〃ー〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(670, "(〃ω〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(671, "(〃艸〃)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(672, "(´つヮ⊂)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(673, "(♡´艸`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(674, "(／≧ω＼)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(675, "ʕ*ﾉᴥﾉʔ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(676, "(/へ＼*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(677, "(*ﾉ▽ﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(678, "(*ﾉωﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(679, "(*ﾉдﾉ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(680, "(´～｀ヾ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(681, "(ﾉ∇≦*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(682, "(‘-’*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(683, "(^◇^；)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(684, "|▽//)ゝ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(685, "(〃´∀｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(686, "ꈍ .̮ ꈍ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(687, "(〃∀〃)ゞ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(688, "( 〃．．)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(689, "(｡･･｡)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(690, "|´∀｀●)"));        }
        else if (i == 10) {
            getSupportActionBar().setTitle("Other");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(691, "( ͡ຈ╭͜ʖ╮͡ຈ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(692, "( ͡ಠ ʖ̯ ͡ಠ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(693, "( ͡~ ͜ʖ ͡~)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(694, "( ͡~ ͜ʖ ͡°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(695, "( ͠° ͟ʖ ͡°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(696, "( ͡ʘ╭͜ʖ╮͡ʘ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(697, "( ͝סּ ͜ʖ͡סּ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(698, "( ͡ᵔ ͜ʖ ͡ᵔ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(699, "( ͡^ ͜ʖ ͡^ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(700, "[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(701, "( ͡ຈ ͜ʖ ͡ຈ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(702, "( ͡° ʖ̯ ͡°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(703, "( ͡ ͜ʖ ͡ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(704, "(☞ ͡° ͜ʖ ͡°)☞"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(705, "ᕕ( ͡° ͜ʖ ͡° )ᕗ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(706, "( ͡° ͜ʖ ͡°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(707, "( ͡°╭͜ʖ╮͡° )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(708, "(つ ͡° ͜ʖ ͡°)つ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(709, "( ͡⚆ ͜ʖ ͡⚆)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(710, "˓˓ ू༼ ⠁⃘ཀ ⠁⃘ू༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(711, "(▀ ͜ʖ ͡°)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(712, "༼ ºل͟º ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(713, "┌༼ຈل͜ຈ༽┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(714, "༼ ಠل͟ಠ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(715, "୧༼ ͡◉ل͜ ͡◉༽୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(716, "ヽ༼ ಠ益ಠ ༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(717, "༼ ༎ຶ ෴ ༎ຶ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(718, "༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(719, "༼･ิɷ･ิ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(720, "༼ ͒ ̶ ͒༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(721, "༼༼;; ;°;ਊ°;༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(722, "༼( ⁍ืེ – ⁍ื༽༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(723, "༼•͟ ͜ •༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(724, "༼•̃͡ ɷ•̃͡༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(725, "༼ ͒ ͓ ͒༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(726, "༼༭ຶཬ༤ຶ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(727, "༼ꉺˇɷˇꉺ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(728, "༼இɷஇ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(729, "༼✷ɷ✷༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(730, "༼ԾɷԾ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(731, "༼≖ɷ≖༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(732, "༼ꉺ✺ꉺ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(733, "༼ꉺლꉺ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(734, "ヽ༼ຈل͜ຈ༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(735, "༼ꉺ౪ꉺ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(736, "༼ꉺεꉺ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(737, "༼;´༎ຶ ༎ຶ ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(738, "༼⁰o⁰；༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(739, "༼(⁽͇ˊ̑⁾ ἴृ ⁽ˋ̑⁾͇)༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(740, "˓ ू༼ ்ͦ॔ཀ ்ͦ॓ू༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(741, "༼ ु ்ͦ॔ཫ ்ͦ॓༽ु˒˒"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(742, "／༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(743, "༼ ்ͦ॔ཫ ்ͦ॓༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(744, "༼ᶿ᷇ཫᶿ᷆༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(745, "༼  ऀืົཀ  ऀืົ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(746, "༼՟ິͫཀ՟ິͫ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(747, "ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(748, "༼❁ɷ❁༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(749, "༼ ຶཽཀ ຶཽ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(750, "ヽ༼၀-၀༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(751, "༼(❛)㇁(❛)༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(752, "ヽ༼⊙_⊙༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(753, "༼⺤`皿′⺤༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(754, "ヽ༼࿃っ࿃༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(755, "༼⌐■ل͟■༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(756, "༼ง=ಠ益ಠ=༽ง"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(757, "╰༼=ಠਊಠ=༽╯"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(758, "ᕙ༼*◕_◕*༽ᕤ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(759, "ヽ༼ಢ_ಢ༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(760, "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(761, "┌༼ ⊘ _ ⊘ ༽┐"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(762, "༼ : ౦ ‸ ౦ : ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(763, "༼∗ღ۝ღ∗༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(764, "༼ง ͠ຈ ͟ل͜ ͠ຈ༽o:[]:::::::>"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(765, "༼ᕗຈل͜ຈ༽ᕗ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(766, "ヽ༼ຈل͜ರೃ༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(767, "ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(768, "༼ ᕤ◕◡◕ ༽ᕤ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(769, "ᕙ༼˵͠ ͠°ل͜͠ ͠°˵༽ᕗ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(770, "ᕦ༼::ಥ෴ಠೃ::༽ノ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(771, "༼ •̀ ں •́ ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(772, "♫ ┌༼ຈل͜ຈ༽┘ ♪"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(773, "༼ ಥل͟ಥ ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(774, "༼ﾉƟ͆ل͜Ɵ͆༽ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(775, "༼୨Ɵ͆ل͜Ɵ͆༽୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(776, "ヽ༼Ɵ͆ل͜Ɵ͆ヽ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(777, "୧༼Ɵ͆ل͜Ɵ͆୧༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(778, "┌༼ຈل͜ຈ༽┘"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(779, "へ༼ ✪ Ĺ̯ ✪ ༽و"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(780, "c༼ ͡° ͜ʖ ͡° ༽⊃"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(781, "༼ ಠ ͟ʖ ಠ ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(782, "୧༼ ” ✖ ‸ ✖ ” ༽୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(783, "Ѱζ༼ᴼل͜ᴼ༽ᶘѰ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(784, "┏༼ ◉ ╭╮ ◉༽┓"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(785, "ヽ༼ ☯‿☯༼ ಠ益ಠ༽◕ل͜◕༽つ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(786, "└༼ •́ ͜ʖ •̀ ༽┘"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(787, "୧༼ ヘ ᗜ ヘ ༽୨"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(788, "༼ ◔ ͜ʖ ◔ ༽"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(789, "╰༼⇀︿⇀༽つ-]═──"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(790, "乁༼☯‿☯✿༽ㄏ"));
        }  else if (i == 11) {
            getSupportActionBar().setTitle("Kiss");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(791, "ㄖꏁㄖ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(792, "ᴓᴈᴓ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(793, "|°з°|"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(794, "(ΦзΦ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(795, "˶⚈Ɛ⚈˵"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(796, "（＿ε＿）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(797, "(‘ε’)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(798, "⁽˙³˙⁾"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(799, "(-ε- )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(800, "•́ε•̀٥"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(801, "(☆´3｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(802, "(・ε・｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(803, " Ⴀ͡კႠ͡"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(804, "(ΘεΘ;)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(805, "(≡ε≡；)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(806, "（￣ε￣＠）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(807, "(´ε｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(808, "（*＾3＾）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(809, "(*￣з￣)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(810, "(○ﾟε^○)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(811, "（。ˇ ⊖ˇ）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(812, "（○゜ε＾○）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(813, "|(￣3￣)|"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(814, "ヾ(´〓｀)ﾉ"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(815, "(~￣³￣)~"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(816, "(ΘεΘʃƪ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(817, "（￣ε￣ʃƪ）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(818, "（＠ーεー＠）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(819, "(*-(　　)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(820, "(๑♡3♡๑)"));
        }else if (i == 12) {
            getSupportActionBar().setTitle("Smile");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(821, "＾ω＾"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(822, "▼ω▼"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(823, "(´∀｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(824, "（＾∀＾）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(825, "(^○^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(826, "(｀▽´)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(827, "米＾－＾米"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(828, "(∩_∩)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(829, "(⌒∇⌒)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(830, "(☆▽☆)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(831, "(￣∇￣)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(832, "（￣ー+￣）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(833, "σ(^○^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(834, "(^■^*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(835, "(*^-^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(836, "d(^^*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(837, "(´w｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(838, "|*￣ー￣|"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(839, "{*≧∀≦}"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(840, "(o^^o)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(841, "(o^∀^)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(842, "(*´ー`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(843, "o(^▽^)o"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(844, "o(^-^)o"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(845, "(*´∇｀*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(846, "（*´▽`*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(847, "(=^_^=)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(848, "σ(ﾟｰ^*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(849, "（●＞ω＜●）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(850, "y（^ヮ^）y"));
        }
        else if (i == 13) {
            getSupportActionBar().setTitle("Laugh");
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(851, "(खਉख)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(852, "(ಡ艸ಡ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(853, "（⌒▽⌒）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(854, "（＾ｖ＾）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(855, "（＞ｙ＜）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(856, "(＾艸＾)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(857, "(Ŏ艸Ŏ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(858, "(亝艸亝)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(859, "(♡´艸`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(860, "(●´艸`)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(861, "(≧艸≦*)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(862, "(*>艸<)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(863, "( ਊдਊ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(864, "( ´艸｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(865, "(｡ˇ艸ˇ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(866, "(o>艸<)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(867, "(^ц^ )"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(868, "(☆Θ艸Θ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(869, "（○´艸｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(870, "(*´艸｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(871, "（≧ｙ≦＊）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(872, "(*・艸・)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(873, "（　´∀｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(874, "(*≧艸≦)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(875, "( ╹ਊ╹)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(876, "( ՞ਊ՞)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(877, "(*´∀｀）"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(878, "(✪ฺܫ✪ฺ)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(879, "( 〃´艸｀)"));
            emotiModeldsfdsfs.add(new EmotiModeldsfdsf(880, "(❤ฺ￫艸￩)"));
        }

        recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(new EmoticonsAdaptersdfs(emotiModeldsfdsfs,this));
    }
}